In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\users\vedan\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vedan\anaconda3\lib\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vedan\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vedan\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vedan\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vedan\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [23]:
import pandas as pd

In [24]:
filepath = r"https://drive.google.com/file/d/1gtMmXUZAlvY0rqg3_q8QUpYWzPClMyPH/view?usp=sharing"

In [25]:
df = pd.read_csv(filepath)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   VendorID               100000 non-null  int64
 1   tpep_pickup_datetime   100000 non-null  object
 2   tpep_dropoff_datetime  100000 non-null  object
 3   passenger_count        100000 non-null  int64
 4   trip_distance          100000 non-null  float64
 5   pickup_longitude       100000 non-null  float64
 6   pickup_latitude        100000 non-null  float64
 7   RatecodeID             100000 non-null  int64
 8   store_and_fwd_flag     100000 non-null  object
 9   dropoff_longitude      100000 non-null  float64
 10  dropoff_latitude       100000 non-null  float64
 11  payment_type           100000 non-null  int64
 12  fare_amount            100000 non-null  float64
 13  extra                  100000 non-null  float64
 14  mta_tax                100000 non-null  float64
 15  tip_amount             100000 non-null  float64
 16  tolls_amount           100000 non-null  float64
 17  improvement_surcharge  100000 non-null  float64
 18  total_amount           100000 non-null  float64
dtypes: float64(12), int64(4), object(3)
memory usage: 14.5+ MB

In [27]:
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

In [28]:
df = df.drop_duplicates().reset_index(drop=True)
df['trip_id'] = df.index

In [29]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,trip_id
0,1,2016-03-01,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35,0
1,1,2016-03-01,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35,1
2,2,2016-03-01,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80,2
3,2,2016-03-01,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62,3
4,2,2016-03-01,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80,4

In [30]:
datetime_dim = df[['tpep_pickup_datetime','tpep_dropoff_datetime']].reset_index(drop=True)
datetime_dim['tpep_pickup_datetime'] = datetime_dim['tpep_pickup_datetime']
datetime_dim['pickup_hour'] = datetime_dim['tpep_pickup_datetime'].dt.hour
datetime_dim['pickup_day'] = datetime_dim['tpep_pickup_datetime'].dt.day
datetime_dim['pickup_month'] = datetime_dim['tpep_pickup_datetime'].dt.month
datetime_dim['pickup_year'] = datetime_dim['tpep_pickup_datetime'].dt.year
datetime_dim['pickup_weekday'] = datetime_dim['tpep_pickup_datetime'].dt.weekday

datetime_dim['tpep_dropoff_datetime'] = datetime_dim['tpep_dropoff_datetime']
datetime_dim['dropoff_hour'] = datetime_dim['tpep_dropoff_datetime'].dt.hour
datetime_dim['dropoff_day'] = datetime_dim['tpep_dropoff_datetime'].dt.day
datetime_dim['dropoff_month'] = datetime_dim['tpep_dropoff_datetime'].dt.month
datetime_dim['dropoff_year'] = datetime_dim['tpep_dropoff_datetime'].dt.year
datetime_dim['dropoff_weekday'] = datetime_dim['tpep_dropoff_datetime'].dt.weekday

In [32]:
datetime_dim['datetime_id'] = datetime_dim.index

In [34]:
datetime_dim = datetime_dim[['datetime_id', 'tpep_pickup_datetime', 'pickup_hour', 'pickup_day', 'pickup_month', 'pickup_year', 'pickup_weekday',
                             'tpep_dropoff_datetime', 'dropoff_hour', 'dropoff_day', 'dropoff_month', 'dropoff_year', 'dropoff_weekday']]

In [35]:
datetime_dim

,datetime_id,tpep_pickup_datetime,pickup_hour,pickup_day,pickup_month,pickup_year,pickup_weekday,tpep_dropoff_datetime,dropoff_hour,dropoff_day,dropoff_month,dropoff_year,dropoff_weekday
0,0,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:07:55,0,1,3,2016,1
1,1,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:11:06,0,1,3,2016,1
2,2,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:31:06,0,1,3,2016,1
3,3,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:00:00,0,1,3,2016,1
4,4,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:00:00,0,1,3,2016,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:22:15,6,1,3,2016,1
99996,99996,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:32:41,6,1,3,2016,1
99997,99997,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:37:23,6,1,3,2016,1
99998,99998,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:22:09,6,1,3,2016,1
99999,99999,2016-03-01 06:17:11,6,1,3,2016,1,2016-03-01 06:22:00,6,1,3,2016,1

In [42]:
passenger_count_dim = df[['passenger_count']].drop_duplicates().reset_index(drop=True)
passenger_count_dim['passenger_count_id'] = passenger_count_dim.index
passenger_count_dim = passenger_count_dim[['passenger_count_id','passenger_count']]

trip_distance_dim = df[['trip_distance']].drop_duplicates().reset_index(drop=True)
trip_distance_dim['trip_distance_id'] = trip_distance_dim.index
trip_distance_dim = trip_distance_dim[['trip_distance_id', 'trip_distance']]

In [43]:
passenger_count_dim.head()

   passenger_count_id  passenger_count
0                   0                1
1                   1                2
2                   2                3
3                   3                5
4                   4                6

Creating RateCode dimension table according to MetaData

In [64]:
rate_code_type = {
    1:"Standard rate",
    2:"JFK",
    3:"Newark",
    4:"Nassau or Westchester",
    5:"Negotiated fare",
    6:"Group ride",
    99:"Null/Unknown"
}

rate_code_dim = df[['RatecodeID']].drop_duplicates().reset_index(drop=True)
rate_code_dim['rate_code_id'] = rate_code_dim.index
rate_code_dim['rate_code_name'] = rate_code_dim['RatecodeID'].map(rate_code_type)
rate_code_dim = rate_code_dim[['rate_code_id', 'RatecodeID', 'rate_code_name']]

In [45]:
rate_code_dim.head()

   rate_code_id  RatecodeID         rate_code_name
0             0           1          Standard rate
1             1           3                 Newark
2             2           2                    JFK
3             3           5        Negotiated fare
4             4           4  Nassau or Westchester

Creating Pickup & Dropoff location dimension table

In [46]:
pickup_location_dim = df[['pickup_longitude', 'pickup_latitude']].drop_duplicates().reset_index(drop=True)
pickup_location_dim['pickup_location_id'] = pickup_location_dim.index
pickup_location_dim = pickup_location_dim[['pickup_location_id', 'pickup_longitude', 'pickup_latitude']]

dropoff_location_dim = df[['dropoff_longitude', 'dropoff_latitude']].drop_duplicates().reset_index(drop=True)
dropoff_location_dim['dropoff_location_id'] = dropoff_location_dim.index
dropoff_location_dim = dropoff_location_dim[['dropoff_location_id', 'dropoff_longitude', 'dropoff_latitude']]

In [47]:
pickup_location_dim.head()

   pickup_location_id  pickup_longitude  pickup_latitude
0                   0        -73.976746        40.765152
1                   1        -73.983482        40.767925
2                   2        -73.782021        40.644810
3                   3        -73.863419        40.769814
4                   4        -73.971741        40.792183

In [48]:
dropoff_location_dim.head()

   dropoff_location_id  dropoff_longitude  dropoff_latitude
0                    0         -74.004265         40.746128
1                    1         -74.005943         40.733166
2                    2         -73.974541         40.675770
3                    3         -73.969650         40.757767
4                    4         -74.177170         40.695053

Payment Dimension Table

In [57]:
payment_type_name = {
    1:"Flex Fare trip",
    2:"Credit card",
    3:"Cash",
    4:"No charge", 
    5:"Dispute", 
    6:"Unknown", 
    7:"Voided trip"
}

payment_type_dim = df[['payment_type']].drop_duplicates().reset_index(drop=True)
payment_type_dim['payment_type_id'] = payment_type_dim.index
payment_type_dim['payment_type_name'] = payment_type_dim['payment_type'].map(payment_type_name)
payment_type_dim = payment_type_dim[['payment_type_id', 'payment_type', 'payment_type_name']]

In [60]:
payment_type_dim

   payment_type_id  payment_type payment_type_name
0                0             1    Flex Fare trip
1                1             2       Credit card
2                2             3              Cash
3                3             4         No charge

Creating FACT Table

In [85]:
fact_table = df.merge(passenger_count_dim, on='passenger_count') \
.merge(trip_distance_dim, on='trip_distance') \
    .merge(rate_code_dim, on='RatecodeID') \
    .merge(pickup_location_dim, on=['pickup_longitude', 'pickup_latitude']) \
    .merge(dropoff_location_dim, on=['dropoff_longitude', 'dropoff_latitude']) \
    .merge(datetime_dim, on=['tpep_pickup_datetime', 'tpep_dropoff_datetime']) \
    .merge(payment_type_dim, on='payment_type') \
    [['trip_id','VendorID', 'datetime_id', 'passenger_count_id', 'trip_distance_id','store_and_fwd_flag', 'rate_code_id', 'pickup_location_id', 'dropoff_location_id',
  'payment_type_id', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount']]

In [86]:
fact_table

,trip_id,VendorID,datetime_id,passenger_count_id,trip_distance_id,store_and_fwd_flag,rate_code_id,pickup_location_id,dropoff_location_id,payment_type_id,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,0,1,0,0,0,N,0,0,0,0,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,1,1,0,1,N,0,1,1,0,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2,2,1,2,N,0,2,2,0,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,3,2,3,2,3,N,0,3,3,0,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,3,2,4,2,3,N,0,3,3,0,31.5,0.0,0.5,3.78,5.54,0.3,41.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100297,99995,1,99995,0,19,N,0,98050,98412,1,5.0,0.0,0.5,0.00,0.00,0.3,5.80
100298,99996,1,99996,0,71,N,0,98051,98413,0,14.0,0.0,0.5,2.00,0.00,0.3,16.80
100299,99997,1,99997,0,295,N,0,98052,98414,0,29.0,0.0,0.5,8.80,5.54,0.3,44.14
100300,99998,2,99998,0,152,N,0,98053,98415,0,5.5,0.5,0.5,1.36,0.00,0.3,8.16
100301,99999,1,99999,0,29,N,0,98054,98416,1,6.0,0.0,0.5,0.00,0.00,0.3,6.80